### ISSUE TITLE
Inserting into db

### ISSUE THREAD

**Issue by MelizzaP** [remember-me/rsvpeanut-api#3]
work on inserting info from API's into database

**Comment by JMGoldsmith** [comment]
Waiting on testing

**Comment by JMGoldsmith** [comment]
waiting on post request, skeleton of wishful code is built.

**Comment by flexyford** [comment]
I have successfully made a post request (in fact too many) to the users db, and have gotten back content! However, the content is not formatted correctly, please see Issue #33 

Thanks John, for the skeleton of wishful code!
