### ISSUE TITLE
Post Request Return non-Ember-Compliant Data

### ISSUE THREAD

**Issue by flexyford** [remember-me/rsvpeanut-api#33]
A post Request to 
POST /users works correctly and is stored in the database! Hooray!

However, the data which is returned is in a format Ember does not expect. 

Current Returned Data:
{"id":29,"password":"test","created_at":"2015-01-31T16:45:44.067Z","updated_at":"2015-01-31T16:45:44.067Z","first":"Tester","last":"McTestingstong","email":"test@test.com"}

Requested Style:
{ "user":
    {"id":29,"password":"test","created_at":"2015-01-31T16:45:44.067Z","updated_at":"2015-01-31T16:45:44.067Z","first":"Tester","last":"McTestingstong","email":"test@test.com"}
}

See http://emberjs.com/api/data/classes/DS.ActiveModelSerializer.html for more details

**Comment by flexyford** [comment]
I think the solution should be done in the app/controllers/users_controller.rb

Line 8: format.json { render :json => @newUser }

should be . . . 

Line 8: format.json { render :json => {:user => @newUser } }

Please add and push to heroku!

**Comment by JMGoldsmith** [comment]
{"user":{"id":18,"password":"app123","created_at":"2015-01-31T18:22:51.753Z","updated_at":"2015-01-31T18:22:51.753Z","first":"firstname","last":"lastname","email":"email@email.com"}}

is now being returned. Issuing pull request for code review and deployment to heroku. 

Alex - please feel free to test my branch using local server. Be sure to assign different ports to the ember server and rails server to avoid conflicts. Events has been altered too to return in the same format.
