### ISSUE TITLE
Create endpoint for Events

### ISSUE THREAD

**Issue by JMGoldsmith** [remember-me/rsvpeanut-api#4]

**Comment by JMGoldsmith** [comment]
will need post permissions for all data, need to see how to have ember send us the json and how we can accept it from a single source.
possible use of auth?

**Comment by MelizzaP** [comment]
I think it will be coming through url so it will look something like - rsvpeanutapi.com?zipcode=78783&radius=1mi

**Comment by JMGoldsmith** [comment]
Needs testing for create method.

**Comment by JMGoldsmith** [comment]
needs to have the api request passed through
